project_name: 'kindle-send'

builds:
  - main: './main.go'
    binary: 'kindle-send'
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64', 'arm64']
    env: 
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X github.com/smoqadam/kindle-send/util.version={{.Version}} -X github.com/smoqadam/kindle-send/util.buildDate={{.Date}}

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', 'Merge pull request', 'Merge branch']

archives:
  - format_overrides:
    - goos: 'windows'
      format: 'zip'

brews:
  - 
    tap:
      owner: 'nikhil1raghav'
      name: 'homebrew-tap'
    folder: 'Formula'
